### PR TITLE
[ITSM-156] 2023.2.0-hotFix

### PR DESCRIPTION
**Pull request by asaccool**
https://pharmaledger.atlassian.net/browse/EPI-629 
https://pharmaledger.atlassian.net/browse/EPI-641

### CODE REVIEW

**Review by PL-Marco — APPROVED** [review]
Reviewed by the tech lead

**Review by S-J-Andrews — APPROVED** [review]
QA approved.

**Review by PL-Marco — APPROVED** [review]
Reviewed by Tech Lead

**Review by S-J-Andrews — APPROVED** [review]
QA Approved.

**Pull request merged**
